services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/snippets/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
        networks:
            - laravel

    php:
#        image: sni10per/tasks-php:1.0.1
        image: tasks-php:latest
#        Uncomment for local project files uses with docker volumes
        build:
            context: .
            dockerfile: Dockerfile

        container_name: php

#        Uncomment for local project files uses with docker volumes
        environment:
            APP_ENV: local
            APP_DEBUG: true
            DB_HOST: mysql
            DB_DATABASE: task_management
            DB_USERNAME: root
            DB_PASSWORD: root
            PHP_IDE_CONFIG: "serverName=local-debug"

#        env_file:
#            - .env

#        Uncomment for local project files uses with docker volumes
        volumes:
            - .:/var/www
            - ./nginx/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
            - ./nginx/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf

        working_dir: /var/www
        networks:
            - laravel
        expose:
            - 9000
        depends_on:
            - mysql
            - redis

    mysql:
        image: mysql:8.0.33
        container_name: mysql
        environment:
            MYSQL_DATABASE: task_management
            MYSQL_USER: user1
            MYSQL_PASSWORD: user1
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./dbdata/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

    redis:
        image: redis:7.0.7
        container_name: redis
        volumes:
            - ./dbdata/redis:/data
        ports:
            - "6379:6379"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    dbdata:
